/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ExceptionsRouteImport } from './routes/exceptions'
import { Route as DemoFlowRouteImport } from './routes/demo-flow'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioPropertyIdRouteImport } from './routes/portfolio.$propertyId'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'

const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsRoute = ExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFlowRoute = DemoFlowRouteImport.update({
  id: '/demo-flow',
  path: '/demo-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioPropertyIdRoute = PortfolioPropertyIdRouteImport.update({
  id: '/$propertyId',
  path: '/$propertyId',
  getParentRoute: () => PortfolioRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo-flow': typeof DemoFlowRoute
  '/exceptions': typeof ExceptionsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/portfolio/$propertyId': typeof PortfolioPropertyIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo-flow': typeof DemoFlowRoute
  '/exceptions': typeof ExceptionsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/portfolio/$propertyId': typeof PortfolioPropertyIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo-flow': typeof DemoFlowRoute
  '/exceptions': typeof ExceptionsRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/portfolio/$propertyId': typeof PortfolioPropertyIdRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo-flow'
    | '/exceptions'
    | '/portfolio'
    | '/portfolio/$propertyId'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo-flow'
    | '/exceptions'
    | '/portfolio'
    | '/portfolio/$propertyId'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/demo-flow'
    | '/exceptions'
    | '/portfolio'
    | '/portfolio/$propertyId'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoFlowRoute: typeof DemoFlowRoute
  ExceptionsRoute: typeof ExceptionsRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions': {
      id: '/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-flow': {
      id: '/demo-flow'
      path: '/demo-flow'
      fullPath: '/demo-flow'
      preLoaderRoute: typeof DemoFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$propertyId': {
      id: '/portfolio/$propertyId'
      path: '/$propertyId'
      fullPath: '/portfolio/$propertyId'
      preLoaderRoute: typeof PortfolioPropertyIdRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortfolioRouteChildren {
  PortfolioPropertyIdRoute: typeof PortfolioPropertyIdRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioPropertyIdRoute: PortfolioPropertyIdRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoFlowRoute: DemoFlowRoute,
  ExceptionsRoute: ExceptionsRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
